### PR TITLE
Add ability to create a copy constructor

### PR DESCRIPTION
**Pull request by c-mansfield**
This PR adds the ability for a copy constructor as seen below.

`    public static final class RecordABuilder {
        private String fieldOne;
        private String fieldTwo;

        private RecordABuilder() {
        }

        private RecordABuilder(RecordA recordA) {
            this.fieldOne = recordA.fieldOne();
            this.fieldTwo = recordA.fieldTwo();
        }
     ...
  }`
  
Currently an optional feature through the ui popup.

### CODE REVIEW

**Comment by c-mansfield** [comment]
Hey @mjedynak, when you get a minute could you please take a look at this PR 😃

**Comment by mjedynak** [comment]
hi @c-mansfield, thanks for the PR, I'll try to look at it shortly.

**Comment by mjedynak** [comment]
I cherry picked your commits as there were some issues (generated code was not compiling in case of using single field and copy constructor) that I fixed myself. 
Released in 1.4.0.

**Comment by c-mansfield** [comment]
Thank you @mjedynak

**Pull request closed without merging**
